[
#goal 1
{X: 8.0, Y: -2.0 , Z: 0.00, theta: 0.037},



#goal 2
{X: 8.24, Y: 2.73 , Z: 0.00, theta: 1.49}


#X: 1.0, Y: 2.0, theta: 90.0}
#{X: 2.0, Y: 2.0, theta: 0.0},
#{X: 3.0, Y: 2.0, theta: 90.0},
#{X: 4.0, Y: 2.0, theta: 0.0}
]